name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master

    - name: Generate xcodeproj
      run: swift package generate-xcodeproj

    - name: Run tests
      run: set -o pipefail && xcodebuild test -scheme swift-nio-mqtt-Package -destination name="iPhone 11" -enableCodeCoverage YES -derivedDataPath .build/derivedData | xcpretty

    - name: Upload MQTTCodec code coverage
      run: bash <(curl -s https://codecov.io/bash) -J '^MQTTCodec$' -D .build/derivedData -t $CODECOV_TOKEN
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload NIOMQTTClient code coverage
      run: bash <(curl -s https://codecov.io/bash) -J '^NIOMQTTClient$' -D .build/derivedData -t $CODECOV_TOKEN
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  buildUbuntu:

    runs-on: ubuntu-18.04
    env:
      Swift_Version: 5.2

    steps:
    - uses: actions/checkout@master

    - name: Install Swift
      run: |
        wget -q https://swift.org/builds/swift-${{ env.Swift_Version }}-release/ubuntu1804/swift-${{ env.Swift_Version }}-RELEASE/swift-${{ env.Swift_Version }}-RELEASE-ubuntu18.04.tar.gz
        tar xzf swift-${{ env.Swift_Version }}-RELEASE-ubuntu18.04.tar.gz
        echo "::add-path::$GITHUB_WORKSPACE/swift-${{ env.Swift_Version }}-RELEASE-ubuntu18.04/usr/bin" 
        
    - name: Run tests
      run: |
        swift build --build-tests --enable-test-discovery
        swift test --enable-test-discovery
